version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    # or you can try "jenkins/jenkins:lts" if you want the latest LTS with Java 11
    user: root
    ports:
      - "8080:8080"       # Jenkins UI
      - "50000:50000"     # For Jenkins agents, if you use distributed builds
    volumes:
      - jenkins_home:/var/jenkins_home
      # (Optional) Mount Docker socket if Jenkins needs to build Docker images
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  mongo-data:
  jenkins_home:
